### ISSUE TITLE
Clickable information for gages on map

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/TravelTime#200] opened 2021-02-22 20:45 UTC
Make the gages clickable and provide links to NWIS, gagestats etc.

![image](https://user-images.githubusercontent.com/16928289/108767904-3e4d9680-7514-11eb-8140-51731c9b11bc.png)

**Comment by tim7en** [comment] 2021-02-24 09:37
Added

**Comment by tgross-usgs** [comment] 2021-03-11 16:22
Duplicate of #189. Closing

**Closed as completed by tgross-usgs** 2021-03-11 16:22 UTC
