### ISSUE TITLE
Response curve charts

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/TravelTime#201] opened 2021-02-22 20:46 UTC
Reach group is not visible

![image](https://user-images.githubusercontent.com/16928289/108768032-66d59080-7514-11eb-8b8a-bbbb875f3062.png)

**Comment by tgross-usgs** [comment] 2021-03-18 12:24
This is a duplicate of issue #181 - closing

**Closed as completed by tgross-usgs** 2021-03-18 12:24 UTC
