### ISSUE TITLE
Downstream trace not working 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/TravelTime#148] opened 2020-09-15 16:40 UTC
getting this on the test client multiple times
![image](https://user-images.githubusercontent.com/12058013/93239355-4674ff00-f748-11ea-903b-ccdcb9e04969.png)

**Comment by HansVraga** [comment] 2020-09-16 20:09
Fair amount of troubleshooting going on around this. 
One avenue is to investigate this suggestion from NLDI team:
NOTE that you should switch over to the “navigation” end point… write up of changes here. https://webvadevvs04.er.usgs.gov/updates/nldi_update/

**Comment by tgross-usgs** [comment] 2021-02-03 13:53
Duplicate of #165

**Closed as completed** 2021-02-03 13:52 UTC
